In [2]:
import numpy as np

#1

In [4]:
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


#2


In [6]:
matrix = np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#3

In [12]:
array_5x5 = np.random.randint(1, 11, size = (5, 5))
print(array_5x5)

[[ 4  1  4  6  1]
 [ 3  4  9  2  4]
 [ 4  4  8  1  2]
 [10 10  1  5  8]
 [ 4  3  8  3  1]]


#4

In [16]:
array_4x4 = np.random.randint(0,2, size = (4, 4))
print(array_4x4)

[[1 1 1 1]
 [1 0 1 1]
 [0 0 1 0]
 [0 1 1 0]]


#5

In [18]:
vector_1 = np.random.randint(1, 11, size = (5, ))
vector_2 = np.random.randint(1, 11, size = (5, ))
print(vector_1 + vector_2)
print(vector_1 - vector_2)
print(vector_1 * vector_2)

[10  8 13 11 15]
[ 0  0 -3 -1  3]
[25 16 40 30 54]


#6

In [19]:
vector_1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector_2 = np.array([7, 6, 5, 4, 3, 2, 1])
print(np.dot(vector_1,vector_2))

84


#7

In [23]:
matrix_1 = np.random.randint(1,11, size = (2,2))
matrix_2 = np.random.randint(1,11, size = (2,3))
print(np.dot(matrix_1,matrix_2))

[[33 44 52]
 [39 52 62]]


#8

In [29]:
matrix = np.random.randint(1,11, size = (3,3))
print(np.linalg.inv(matrix))

[[ 0.0921659  -0.17511521  0.11520737]
 [-0.28571429  0.14285714  0.14285714]
 [ 0.13364055  0.04608295 -0.08294931]]


#9

In [32]:
matrix = np.random.randint(0,2, size = (4,4))
print(matrix.T)

[[0 1 0 0]
 [0 0 0 0]
 [1 1 0 1]
 [0 1 1 1]]


#10

In [36]:
matrix = np.random.randint(1,11 , size = (3,4))
vector = np.random.randint(1,11 , size = (4, ))
print(matrix * vector)

[[18 25 15  6]
 [20 20 24 24]
 [ 6 10  6 18]]


#11

In [39]:
matrix = np.random.randint(0,2 , size = (2,3))
vector = np.random.randint(0,2 , size = (3, ))
print(matrix * vector)

[[0 1 1]
 [0 1 1]]


#12

In [40]:
matrix_1 = np.random.randint(1,11 , size = (2,2))
matrix_2 = np.random.randint(1,11 , size = (2,2))
print(matrix_1 * matrix_2)

[[20 30]
 [ 1 70]]


#13

In [42]:
matrix_1 = np.random.randint(1,11 , size = (2,2))
matrix_2 = np.random.randint(1,11 , size = (2,2))
print(np.dot(matrix_1, matrix_2))

[[ 66  73]
 [ 50 113]]


#14

In [45]:
matrix = np.random.randint(1,101 , size = (5,5))
print(sum(matrix))

[296 289 215 203 242]


#15

In [47]:
matrix_1 = np.random.randint(1,11 , size = (4,4))
matrix_2 = np.random.randint(1,11 , size = (4,4))
print(matrix_1 - matrix_2)

[[ 1  9 -2 -4]
 [-3 -1  1 -2]
 [ 2  4 -2  2]
 [-2  0  3  3]]


#16

In [65]:
matrix = np.random.randint(0,2, size =(3, 3))
row_sums = np.sum(matrix,axis = 1).reshape(-1,1)
print(row_sums)

[[3]
 [1]
 [2]]


#17

In [66]:
matrix = np.random.randint(-10, 11, size=(3, 4))
squared_matrix = np.power(matrix, 2)
print(squared_matrix)


[[ 9 25 36 16]
 [25 81 25 16]
 [ 4  0 16  4]]


#18

In [71]:
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)
print(sqrt_vector)

[5.56776436 5.         2.         2.44948974]
