In [1]:
import numpy as np

#1

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#2

In [9]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#3

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
vertical_stack = np.vstack((a, b))
print(vertical_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#4

In [39]:
a = np.array([1, 2, 3])
n_repeats = len(a)
repeated_elements= np.repeat(a, n_repeats)
result = np.array(repeated_elements)
for _ in range(n_repeats):
    result = np.append(result,a)
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


#5

In [40]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_elements = np.intersect1d(a, b)
print(common_elements)

[2 4]


#6

In [42]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
sorted_indices = np.argsort(a)
top_5_indices = sorted_indices[-5:]
top_5_indices_sorted = np.sort(top_5_indices)
print(top_5_indices_sorted)

[ 3  7 10 15 18]


#7

In [43]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = a[~np.isnan(a)]
print(a_clean)

[1. 2. 3. 5. 6. 7.]


#8

In [44]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
distance = np.sqrt(np.sum((a - b) ** 2))
print(distance)

6.708203932499369


#9

In [49]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
if len(indices) >= 5:
    fifth_occurrence_index = indices[4]
    print(fifth_occurrence_index)

8


#10

In [51]:
a = np.random.randint(0, 5, 10)
unique_elements, first_occurrence_indices = np.unique(a, return_index=True)
result = np.zeros_like(a, dtype=bool)
for idx in first_occurrence_indices:
    result[a == a[idx]] = True
    result[idx] = False
print(result)

[False False  True False False  True False  True  True  True]
